#!/bin/sh
#
# Push the current branch after a successful merge.
# This covers merge commits that are not handled by post-commit on some setups.

hook_dir="$(dirname "$0")"

if [ -x "$hook_dir/post-commit" ]; then
  "$hook_dir/post-commit"
else
  sh "$hook_dir/post-commit"
fi
